name: Fortify on Demand SAST Scan

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven
      - name: Run FoD SAST Scan
        uses: fortify/github-action/fod-sast-scan@v2
        env:
          FOD_URL: ${{secrets.FOD_URL}}
          # FOD_TENANT: ${{secrets.FOD_TENANT}}
          # FOD_USER: ${{secrets.FOD_USER}}
          # FOD_PASSWORD: ${{secrets.FOD_PAT}}
          FOD_CLIENT_ID: ${{secrets.FOD_API_KEY}}
          FOD_CLIENT_SECRET: ${{secrets.FOD_API_SECRET}}
          # FOD_LOGIN_EXTRA_OPTS: --socket-timeout=60s
          FOD_RELEASE: ${{secrets.FOD_RELEASE_ID}}
          # DO_SETUP: true
          # SETUP_ACTION: https://scm.my.org/shared-repos/fcli-actions/setup.yaml
          # SETUP_EXTRA_OPTS: --copy-from "${{ github.repository }}:${{ github.event.repository.default_branch }}"
          SC_CLIENT_VERSION: 25.4.0
          DO_PACKAGE_DEBUG: true
          PACKAGE_EXTRA_OPTS: -oss -bt mvn
          # FOD_SAST_SCAN_EXTRA_OPTS:
          # DO_DEBRICKED_SCAN: true
          # DO_WAIT: true
          # DO_POLICY_CHECK: true
          # POLICY_CHECK_ACTION: https://scm.my.org/shared-repos/fcli-actions/check-policy.yaml
          # POLICY_CHECK_EXTRA_OPTS: --on-unsigned=ignore
          # DO_JOB_SUMMARY: true
          # JOB_SUMMARY_ACTION: https://scm.my.org/shared-repos/fcli-actions/job-summary.yaml
          # JOB_SUMMARY_EXTRA_OPTS: --on-unsigned=ignore
          # DO_PR_COMMENT: true
          # PR_COMMENT_ACTION: https://scm.my.org/shared-repos/fcli-actions/github-pr-comment.yaml
          # PR_COMMENT_EXTRA_OPTS: --on-unsigned=ignore
          DO_EXPORT: true
          # EXPORT_ACTION: https://scm.my.org/shared-repos/fcli-actions/github-sast-report.yaml
          # EXPORT_EXTRA_OPTS: --on-unsigned=ignore
          # TOOL_DEFINITIONS: https://ftfy.mycompany.com/tool-definitions/v1/tool-definitions.yaml.zip
